export type PublicJsonValue =
  string | number | boolean | null | readonly PublicJsonValue[] | PublicJsonObject;
export interface PublicJsonObject {
  readonly [key: string]: PublicJsonValue;
}
export interface WritableJsonObject {
  readonly [key: string]: PublicJsonValue;
}

export interface ListPatientConsentsResponse {
  readonly consents: readonly PublicJsonObject[];
  readonly enforcementState: PublicJsonObject;
}

export interface GetEncounterResponse {
  readonly encounter: PublicJsonObject;
  readonly noteVersions: readonly PublicJsonObject[];
}

export interface GetPatientDentalChartResponse {
  readonly dentalChart: PublicJsonObject;
  readonly findings: readonly PublicJsonObject[];
  readonly history: readonly PublicJsonObject[];
  readonly snapshots: readonly PublicJsonObject[];
}

export interface ListPatientMediaAssetsResponse {
  readonly mediaAssets: readonly PublicJsonObject[];
}

export interface CreateSignedMediaAccessResponse {
  readonly mediaAsset: PublicJsonObject;
  readonly access: PublicJsonObject;
}

/**
 * Exact structural subset of the generated ClinicOsApiClient. Composition passes the generated
 * client instance; this feature has no handwritten fetch path or fixture fallback. The structural
 * boundary avoids pulling the generated source into Next until its Uint8Array BodyInit typing is
 * regenerated by the master-owned contract pipeline.
 */
export interface ClinicalDentalGeneratedClient {
  listPatientConsents(input: {
    readonly path: { readonly patientId: string };
  }): Promise<ListPatientConsentsResponse>;
  getEncounter(input: {
    readonly path: { readonly encounterId: string };
  }): Promise<GetEncounterResponse>;
  getPatientDentalChart(input: {
    readonly path: { readonly patientId: string };
  }): Promise<GetPatientDentalChartResponse>;
  listPatientMediaAssets(input: {
    readonly path: { readonly patientId: string };
    readonly query?: { readonly limit?: number };
  }): Promise<ListPatientMediaAssetsResponse>;
  requestMediaUploadUrl(input: {
    readonly headers: { readonly "idempotency-key": string };
    readonly body: {
      readonly patientId: string;
      readonly encounterId?: string | null;
      readonly dentalFindingId?: string | null;
      readonly toothNumber?: string | null;
      readonly mediaType:
        "intraoral_photo" | "xray" | "document" | "audio_chunk" | "generated_document";
      readonly originalFilename: string;
      readonly mimeType: string;
      readonly fileSizeBytes: number;
      readonly sha256Digest?: string | null;
      readonly tags?: readonly string[];
      readonly provenance?: WritableJsonObject;
    };
  }): Promise<{ readonly upload: PublicJsonObject; readonly uploadTarget: PublicJsonObject }>;
  receiveMediaUploadContent(input: {
    readonly path: { readonly uploadId: string };
    readonly headers: { readonly "idempotency-key": string };
    readonly body: Uint8Array;
  }): Promise<{ readonly upload: PublicJsonObject; readonly object: PublicJsonObject }>;
  completeMediaUpload(input: {
    readonly path: { readonly uploadId: string };
    readonly headers: { readonly "idempotency-key": string };
    readonly body: {
      readonly patientId: string;
      readonly encounterId?: string | null;
      readonly contentLength?: number | null;
      readonly sha256Digest?: string | null;
      readonly mimeType?: string | null;
    };
  }): Promise<{ readonly mediaAsset: PublicJsonObject }>;
  createSignedMediaAccess(input: {
    readonly path: { readonly mediaAssetId: string };
    readonly headers: { readonly "idempotency-key": string };
    readonly body: { readonly expiresInSeconds?: number };
  }): Promise<CreateSignedMediaAccessResponse>;
}

export interface ClinicalDentalWorkspaceData {
  readonly patientId: string;
  readonly consents: ListPatientConsentsResponse;
  readonly encounter: GetEncounterResponse | null;
  readonly dental: GetPatientDentalChartResponse;
  readonly media: ListPatientMediaAssetsResponse;
}

export type LatestClinicalDentalWorkspaceLoad =
  | { readonly status: "applied"; readonly data: ClinicalDentalWorkspaceData }
  | { readonly status: "stale" };

export interface LatestClinicalDentalWorkspaceLoader {
  load(
    input: Readonly<{ patientId: string; encounterId?: string | null; mediaLimit?: number }>
  ): Promise<LatestClinicalDentalWorkspaceLoad>;
  invalidate(): void;
}

export interface ClinicalMediaUploadCommand {
  readonly patientId: string;
  readonly encounterId?: string | null;
  readonly dentalFindingId?: string | null;
  readonly toothNumber?: string | null;
  readonly mediaType:
    "intraoral_photo" | "xray" | "document" | "audio_chunk" | "generated_document";
  readonly originalFilename: string;
  readonly mimeType: string;
  readonly bytes: Uint8Array;
  readonly tags?: readonly string[];
  readonly provenance?: WritableJsonObject;
  readonly idempotencyKey: string;
}

export interface ClinicalMediaUploadResult {
  readonly mediaAsset: PublicJsonObject;
  readonly scanStatus: string | null;
}

export type ClinicalCapabilityFailure =
  | { readonly kind: "unavailable"; readonly message: string; readonly requestId: string | null }
  | { readonly kind: "forbidden"; readonly message: string; readonly requestId: string | null }
  | { readonly kind: "error"; readonly message: string; readonly requestId: string | null };

export async function loadClinicalDentalWorkspace(
  client: ClinicalDentalGeneratedClient,
  input: Readonly<{ patientId: string; encounterId?: string | null; mediaLimit?: number }>
): Promise<ClinicalDentalWorkspaceData> {
  const [consents, encounter, dental, media] = await Promise.all([
    client.listPatientConsents({ path: { patientId: input.patientId } }),
    input.encounterId
      ? client.getEncounter({ path: { encounterId: input.encounterId } })
      : Promise.resolve(null),
    client.getPatientDentalChart({ path: { patientId: input.patientId } }),
    client.listPatientMediaAssets({
      path: { patientId: input.patientId },
      query: { limit: input.mediaLimit ?? 50 }
    })
  ]);
  return {
    patientId: input.patientId,
    consents,
    encounter,
    dental,
    media
  };
}

export function createLatestClinicalDentalWorkspaceLoader(
  client: ClinicalDentalGeneratedClient
): LatestClinicalDentalWorkspaceLoader {
  let generation = 0;
  return Object.freeze({
    async load(
      input: Readonly<{ patientId: string; encounterId?: string | null; mediaLimit?: number }>
    ) {
      const loadGeneration = ++generation;
      try {
        const data = await loadClinicalDentalWorkspace(client, input);
        return loadGeneration === generation
          ? { status: "applied" as const, data }
          : { status: "stale" as const };
      } catch (error) {
        if (loadGeneration !== generation) return { status: "stale" as const };
        throw error;
      }
    },
    invalidate() {
      generation += 1;
    }
  });
}

export async function uploadClinicalMedia(
  client: ClinicalDentalGeneratedClient,
  command: ClinicalMediaUploadCommand
): Promise<ClinicalMediaUploadResult> {
  if (command.bytes.byteLength < 1 || command.bytes.byteLength > 100 * 1024 * 1024) {
    throw new RangeError("Clinical media must contain between 1 byte and 100 MiB.");
  }
  const digest = await sha256Hex(command.bytes);
  const reservation = await client.requestMediaUploadUrl({
    headers: { "idempotency-key": `${command.idempotencyKey}:reserve` },
    body: {
      patientId: command.patientId,
      encounterId: command.encounterId,
      dentalFindingId: command.dentalFindingId,
      toothNumber: command.toothNumber,
      mediaType: command.mediaType,
      originalFilename: privateUploadSubmissionFilename(command.originalFilename, command.mimeType),
      mimeType: command.mimeType,
      fileSizeBytes: command.bytes.byteLength,
      sha256Digest: digest,
      tags: command.tags,
      provenance: command.provenance
    }
  });
  const uploadId = requiredPublicString(reservation.upload, "id");
  await client.receiveMediaUploadContent({
    path: { uploadId },
    headers: { "idempotency-key": `${command.idempotencyKey}:content` },
    body: command.bytes
  });
  const completed = await client.completeMediaUpload({
    path: { uploadId },
    headers: { "idempotency-key": `${command.idempotencyKey}:complete` },
    body: {
      patientId: command.patientId,
      encounterId: command.encounterId,
      contentLength: command.bytes.byteLength,
      sha256Digest: digest,
      mimeType: command.mimeType
    }
  });
  return {
    mediaAsset: completed.mediaAsset,
    scanStatus: optionalPublicString(completed.mediaAsset, "scanStatus")
  };
}

export async function requestClinicalMediaAccess(
  client: ClinicalDentalGeneratedClient,
  input: Readonly<{
    mediaAssetId: string;
    idempotencyKey: string;
    expiresInSeconds?: number;
  }>
): Promise<{
  readonly signedUrl: string;
  readonly expiresAt: string;
  readonly response: CreateSignedMediaAccessResponse;
}> {
  const response = await client.createSignedMediaAccess({
    path: { mediaAssetId: input.mediaAssetId },
    headers: { "idempotency-key": input.idempotencyKey },
    body: { expiresInSeconds: input.expiresInSeconds }
  });
  return {
    signedUrl: requiredPublicString(response.access, "signedUrl"),
    expiresAt: requiredPublicString(response.access, "expiresAt"),
    response
  };
}

export function classifyClinicalCapabilityFailure(error: unknown): ClinicalCapabilityFailure {
  if (isGeneratedApiError(error)) {
    if (error.code === "CONFIGURATION_ERROR" || error.code === "DEPENDENCY_UNAVAILABLE") {
      return {
        kind: "unavailable",
        message: error.message,
        requestId: error.requestId || null
      };
    }
    if (error.code === "PERMISSION_DENIED" || error.code === "UNAUTHENTICATED") {
      return { kind: "forbidden", message: error.message, requestId: error.requestId || null };
    }
    return { kind: "error", message: error.message, requestId: error.requestId || null };
  }
  return {
    kind: "error",
    message: error instanceof Error ? error.message : "Clinical workflow request failed.",
    requestId: null
  };
}

export function optionalPublicString(record: PublicJsonObject, name: string): string | null {
  const value = record[name];
  return typeof value === "string" ? value : null;
}

export function requiredPublicString(record: PublicJsonObject, name: string): string {
  const value = optionalPublicString(record, name);
  if (!value) throw new TypeError(`Clinical API response is missing ${name}.`);
  return value;
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as Uint8Array<ArrayBuffer>);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

function privateUploadSubmissionFilename(filename: string, mimeType: string): string {
  const extension = filename
    .trim()
    .toLowerCase()
    .match(/\.([a-z0-9]{1,12})$/u)?.[1];
  const allowed = clientExtensionsForMimeType(mimeType);
  if (!extension || !allowed.includes(extension)) {
    throw new TypeError("Clinical media filename extension does not match its MIME type.");
  }
  return `clinical-upload.${extension}`;
}

function clientExtensionsForMimeType(mimeType: string): readonly string[] {
  switch (mimeType.split(";", 1)[0]?.trim().toLowerCase()) {
    case "image/jpeg":
      return ["jpg", "jpeg"];
    case "image/png":
      return ["png"];
    case "image/webp":
      return ["webp"];
    case "image/heic":
      return ["heic"];
    case "image/heif":
      return ["heif"];
    case "image/tiff":
      return ["tif", "tiff"];
    case "application/pdf":
      return ["pdf"];
    case "application/dicom":
      return ["dcm", "dicom"];
    case "audio/wav":
      return ["wav"];
    case "audio/webm":
      return ["webm"];
    case "audio/mp4":
      return ["m4a", "mp4"];
    case "audio/mpeg":
      return ["mp3", "mpeg"];
    default:
      return [];
  }
}

function isGeneratedApiError(error: unknown): error is Error & {
  readonly code: string;
  readonly requestId: string;
} {
  return (
    error instanceof Error &&
    typeof (error as { code?: unknown }).code === "string" &&
    typeof (error as { requestId?: unknown }).requestId === "string"
  );
}
