flyway.url=jdbc:postgresql://postgres:5432/clinic_os
flyway.user=clinic_os_migrator
flyway.password=clinic_os_migrator
flyway.locations=filesystem:/flyway/sql
flyway.sqlMigrationPrefix=0
flyway.sqlMigrationSeparator=_
flyway.sqlMigrationSuffixes=.sql
flyway.validateMigrationNaming=true
flyway.table=flyway_schema_history
flyway.connectRetries=30
flyway.lockRetryCount=30
flyway.cleanDisabled=true
flyway.outOfOrder=false
flyway.validateOnMigrate=true
